### ISSUE TITLE
Bug: Health check endpoint for the scheduler misbehaves when multiple instances of the scheduler are deployed

### ISSUE THREAD

**Issue by jonasban** [dagu-org/dagu#1156]
Once #1120 and #1130 were implemented in 1.8.5 I tried to enable the health check functionality for the scheduler in the `config.yaml` by specifying the port of `8090` as per docs:

```
host: 0.0.0.0
port: 8080
basePath: ""              # For reverse proxy (e.g., "/dagu")
apiBasePath: "/api/v2"    # API endpoint base path
debug: false
logFormat: "text"         # "text" or "json"
headless: false

scheduler:
  port: 8090
```

Compose file for reference:

```
services:
  ui-1:
    image: dagu:latest
    environment:
      DAGU_HOME: "/home/dagu"
    volumes:
      - ./config.yaml:/home/dagu/config.yaml
      - ./dags:/home/dagu/dags
      - ./data:/home/dagu/data
      - ./logs:/home/dagu/logs
      - ./suspend:/home/dagu/suspend
    ports:
      - 8080:8080
    command: ["server"]

  ui-2:
    image: dagu:latest
    environment:
      DAGU_HOME: "/home/dagu"
    volumes:
      - ./config.yaml:/home/dagu/config.yaml
      - ./dags:/home/dagu/dags
      - ./data:/home/dagu/data
      - ./logs:/home/dagu/logs
      - ./suspend:/home/dagu/suspend
    ports:
      - 8081:8080
    command: ["server"]

  scheduler-1:
    image: dagu:latest
    environment:
      DAGU_HOME: "/home/dagu"
    volumes:
      - ./config.yaml:/home/dagu/config.yaml
      - ./dags:/home/dagu/dags
      - ./data:/home/dagu/data
      - ./logs:/home/dagu/logs
      - ./suspend:/home/dagu/suspend
    command: ["scheduler"]

  scheduler-2:
    image: dagu:latest
    environment:
      DAGU_HOME: "/home/dagu"
    volumes:
      - ./config.yaml:/home/dagu/config.yaml
      - ./dags:/home/dagu/dags
      - ./data:/home/dagu/data
      - ./logs:/home/dagu/logs
      - ./suspend:/home/dagu/suspend
    command: ["scheduler"]
```

In this setup health check endpoint responds  for `scheduler-1` as expected:
```
$ docker exec -it dagu_service-scheduler-1-1 wget -O - 127.0.0.1:8090/health
Connecting to 127.0.0.1:8090 (127.0.0.1:8090)
writing to stdout
{"status":"healthy"}
```
But if I run the same for `scheduler-2` it seems the health endpoint is blocked:
```
docker exec -it dagu_service-scheduler-2-1 wget -O - 127.0.0.1:8090/health
Connecting to 127.0.0.1:8090 (127.0.0.1:8090)
wget: can't connect to remote host (127.0.0.1): Connection refused
```

This means that Docker will be restarting the `scheduler-2` container indefinitely. Can it be that one scheduler instance depends on another somehow? The expected result is that both instances of the scheduler can be checked for healthiness independently.

**Comment by yohamta0** [comment]
@jonasban this should be fixed in the latest version (1.18.6). Could you give it a try? Thanks!

**Comment by jonasban** [comment]
Yes, all good, 1.8.6 works as expected now!

**Comment by yohamta0** [comment]
Glad to hear that, thank you for your confirmation!

**Comment by jonasban** [comment]
Hey! It seems this issue is back with 2.3.0 version - only one instance of the scheduler responds to requests, the others refuse the connection and Docker keeps restarting them because they are deemed unhealthy:

```
$ docker exec -it dagu-scheduler-1 wget -O - 127.0.0.1:8090/health
Connecting to 127.0.0.1:8090 (127.0.0.1:8090)
wget: can't connect to remote host (127.0.0.1): Connection refused

$ docker exec -it dagu-scheduler-2 wget -O - 127.0.0.1:8090/health
Connecting to 127.0.0.1:8090 (127.0.0.1:8090)
wget: can't connect to remote host (127.0.0.1): Connection refused

$ docker exec -it dagu-scheduler-3 wget -O - 127.0.0.1:8090/health
Connecting to 127.0.0.1:8090 (127.0.0.1:8090)
writing to stdout
{"status":"healthy"}
-                    100% |*********************************************|    21  0:00:00 ETA
written to stdout
```

**Comment by yohamta0** [comment]
Thank you for reporting, will fix this soon.

**Comment by jonasban** [comment]
Blazing fast, as always @yottahmd! 🚀

**Comment by jonasban** [comment]
I have tested version 2.3.1 and can confirm that the scheduler health checks are working as expected 👍
